import { useState } from "react";
import type { BackupProvider, BackupSnapshot } from "../types";
import { Icon, ProviderIcon, StatusIcon } from "../components/Icons";

export function BackupsPage({ snapshots, onRestore }: { snapshots: BackupSnapshot[]; onRestore: (s: BackupSnapshot) => void }) { return <div className="page"><PageHead title="Backup history" subtitle="All snapshots across your library"/><div className="page-table">{snapshots.map(s => <div className="page-row" key={s.id}><ProviderIcon type={s.providerId}/><span><strong>{s.gameId}</strong><small>{s.saveTargetId}</small></span><span>{s.timestamp}</span><span>{(s.size/1048576).toFixed(0)} MB</span><button onClick={() => onRestore(s)}><Icon name="restore"/>Restore</button></div>)}</div></div> }
export function ProvidersPage({ providers, onAdd }: { providers: BackupProvider[]; onAdd: () => void }) { return <div className="page"><PageHead title="Providers" subtitle="Backup destinations and connection status" action={<button onClick={onAdd}><Icon name="plus"/>Add local provider</button>}/><div className="provider-grid">{providers.map(p => <div className="provider-card" key={p.id}><ProviderIcon type={p.providerType}/><span><strong>{p.name}</strong><small>{p.destination}</small></span><StatusIcon status={p.connected ? "healthy" : "warning"}/></div>)}<div className="provider-card stub"><ProviderIcon type="drive"/><span><strong>Google Drive</strong><small>Cloud integration · coming soon</small></span></div><div className="provider-card stub"><ProviderIcon type="mega"/><span><strong>MEGA</strong><small>Cloud integration · coming soon</small></span></div></div></div> }
export function ActivityPage() { return <div className="page"><PageHead title="Activity" subtitle="Recent backup operations"/><div className="activity-list"><p><StatusIcon status="healthy"/><span><strong>Backup completed</strong><small>Minecraft · Survival World · Today, 7:42 PM</small></span></p><p><StatusIcon status="healthy"/><span><strong>Provider check passed</strong><small>Local Backups · Today, 7:40 PM</small></span></p><p><StatusIcon status="warning"/><span><strong>Target is not protected</strong><small>Minecraft · Hardcore World</small></span></p></div></div> }
export function SettingsPage() { const [start, setStart] = useState(true); return <div className="page"><PageHead title="Settings" subtitle="Mnemo preferences"/><div className="settings-card"><label><span><strong>Launch at startup</strong><small>Start Mnemo when you sign in</small></span><input type="checkbox" checked={start} onChange={e => setStart(e.target.checked)}/></label><label><span><strong>Check provider health</strong><small>Periodically verify backup destinations</small></span><input type="checkbox" defaultChecked/></label><label><span><strong>Notifications</strong><small>Show a notification when backups complete</small></span><input type="checkbox" defaultChecked/></label></div></div> }
function PageHead({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-head"><span><h1>{title}</h1><p>{subtitle}</p></span>{action}</div> }
